name: 🐛 Bug Report
description: Сообщить об ошибке
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Описание
      description: Что произошло?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Как воспроизвести
      description: Шаги для воспроизведения
  - type: input
    attributes:
      label: Версия
      description: git commit или тег
