"""Automatic error reporting to GitHub Issues."""
import os
import logging
import traceback
import requests
from datetime import datetime
from config import Config

log = logging.getLogger("github_reporter")


class GitHubReporter:
    """Sends bot errors and exceptions as GitHub Issues."""

    def __init__(self, token: str = None, repo: str = None):
        self.token = token or os.getenv("GITHUB_TOKEN", "")
        self.repo = repo or os.getenv("GITHUB_REPO", "Alexkkkkk/GRINCH-GRAM")
        self.api_url = f"https://api.github.com/repos/{self.repo}/issues"
        self.enabled = bool(self.token and self.repo)
        if not self.enabled:
            log.warning("[GitHubReporter] Disabled: no GITHUB_TOKEN or GITHUB_REPO")

    def create_issue(self, title: str, body: str, labels: list = None) -> dict:
        if not self.enabled:
            return {"ok": False, "error": "Reporter disabled"}
        headers = {
            "Authorization": f"token {self.token}",
            "Accept": "application/vnd.github.v3+json"
        }
        payload = {
            "title": f"[BOT ERROR] {title}",
            "body": body,
            "labels": labels or ["bot-error", "auto-report"]
        }
        try:
            resp = requests.post(self.api_url, headers=headers, json=payload, timeout=15)
            if resp.status_code == 201:
                data = resp.json()
                log.info("[GitHubReporter] Issue created: %s", data.get("html_url"))
                return {"ok": True, "issue_url": data.get("html_url"), "issue_number": data.get("number")}
            else:
                log.error("[GitHubReporter] Failed: %s %s", resp.status_code, resp.text)
                return {"ok": False, "error": f"HTTP {resp.status_code}: {resp.text}"}
        except Exception as e:
            log.error("[GitHubReporter] Request failed: %s", e)
            return {"ok": False, "error": str(e)}

    def report_exception(self, exc: Exception, context: str = ""):
        tb = traceback.format_exc()
        title = f"{type(exc).__name__}: {str(exc)[:80]}"
        body = f"""## Bot Exception Report

**Time:** {datetime.utcnow().isoformat()} UTC
**Context:** {context or 'N/A'}
**Symbol:** {Config.SYMBOL}

### Traceback
```python
{tb}
```

### Environment
- Testnet: {Config.USE_TESTNET}
- Symbol: {Config.SYMBOL}
- Grid Count: {Config.GRID_COUNT}

---
*This issue was created automatically by GRINCH-GRAM Grid Bot.*
"""
        return self.create_issue(title, body, labels=["bot-error", "auto-report", "bug"])

    def report_trade_error(self, side: str, level_id: int, price: float, error_msg: str):
        title = f"Trade Failed: {side} @ {price} (Level {level_id})"
        body = f"""## Trade Execution Failure

**Time:** {datetime.utcnow().isoformat()} UTC
**Side:** {side}
**Level ID:** {level_id}
**Price:** {price}
**Error:** {error_msg}
**Symbol:** {Config.SYMBOL}

---
*Auto-generated by GRINCH-GRAM Grid Bot.*
"""
        return self.create_issue(title, body, labels=["bot-error", "trade-failure", "auto-report"])

    def report_grid_rebuild(self, old_center: float, new_center: float, reason: str):
        title = f"Grid Recentered: {old_center:.6f} -> {new_center:.6f}"
        body = f"""## Grid Recentering Event

**Time:** {datetime.utcnow().isoformat()} UTC
**Reason:** {reason}
**Old Center:** {old_center}
**New Center:** {new_center}
**Symbol:** {Config.SYMBOL}

---
*Auto-generated by GRINCH-GRAM Grid Bot.*
"""
        return self.create_issue(title, body, labels=["bot-info", "grid-rebuild", "auto-report"])


_reporter = None

def get_reporter() -> GitHubReporter:
    global _reporter
    if _reporter is None:
        _reporter = GitHubReporter()
    return _reporter
